server:
  port: 9961
spring:
  application:
    name: eurekasrv
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mplus3?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost #eureka 服务端实例名称
  client:
    register-with-eureka: false # 表示不向注册中心注册自己
    fetch-registry: false # 表示自己就是注册中心 维护服务实例 不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/