server:
  port: 9090
spring:
  application:
    name: Chapter01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Chapter01
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.234.140
    port: 6379
    database: 1
    password: '123456'
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'