server:
  port: 9502
spring:
  application:
    name: toolstudy
  redis:
    host: localhost
    port: 6379
    password: '123456'
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
security:
  antiReply:
    timestamp: 5